apiVersion: v1
kind: Service
metadata:
  name: test-service1
  namespace: test
spec:
  selector:
    app: file
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      name: sharer
    - protocol: TCP
      port: 3008
      targetPort: 3008
      name: downloader
  type: ClusterIP