apiVersion: v1
kind: Service
metadata:
  name: test-service1
spec:
  selector:
    app: file
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: sharer
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: downloader
  type: ClusterIP