apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: file
spec:
  containers:
    - name: sharer
      image: 7143192/fileserver:latest
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/files
    - name: downloader
      image: 7143192/downloader:latest
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: shared-data
          mountPath: /data