apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test
  labels:
    app: file
spec:
  containers:
    - name: sharer
      image: docker.io/library/golang:1.20
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/files
    - name: downloader
      image: docker.io/library/golang:1.20
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: shared-data
          mountPath: /data