apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
  namespace: test
  labels:
    app: file
spec:
  containers:
    - name: sharerr
      image: docker.io/library/nginx:latest
      ports:
        - containerPort: 8088
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/files
    - name: downloaderr
      image: docker.io/library/golang:1.20
      ports:
        - containerPort: 3008
      volumeMounts:
        - name: shared-data
          mountPath: /data
          readOnly: true
  volumes:
    - name: shared-data
      hostPath: /root/data