apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
  namespace: test
  labels:
    app: file
spec:
  containers:
    - name: nginx2
      image: docker.io/library/nginx:latest
      ports:
        - containerPort: 8088
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/files
    - name: goland2
      image: docker.io/library/golang:1.20
      ports:
        - containerPort: 3008
      volumeMounts:
        - name: shared-data
          mountPath: /data