apiVersion: v1
kind: Pod
metadata:
  name: test-pod3
  namespace: test
  labels:
    app: file
spec:
  containers:
    - name: nginx2
      image: docker.io/library/nginx:latest
      ports:
        - containerPort: 8088
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/files
      resources:
        limits:
          memory: 128
          cpuNumber: "1"
          cpuCores: "1"
    - name: goland2
      image: docker.io/library/golang:1.20
      ports:
        - containerPort: 3008
      volumeMounts:
        - name: shared-data
          mountPath: /data