apiVersion: v1
kind: Service
metadata:
  name: deployment-service
  namespace: default
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
      name: auto-count
  type: ClusterIP