apiVersion: v1
kind: DNS
name: new-dns
host: example.com
paths:
  - path: /footprint
    serviceNamespace: default
    serviceName: test-service1
    servicePort: 8888
  - path: /nginx
    serviceNamespace: default
    serviceName: nginx-service
    servicePort: 80