apiVersion: v1
kind: DNS
name: new-dns
host: example.com
paths:
  - path: /footprint
    serviceName: test-service1
    servicePort: 8888
  - path: /counter
    serviceName: deployment-service
    servicePort: 12345