apiVersion: v1
kind: HPA
metadata:
  name: test-hpa
  namespace: default
spec:
  minReplica: 2
  maxReplica: 5
  template:
    metadata:
      name: test-hpa-pod
      namespace: default
      labels:
        app: hpa
    spec:
      containers:
        - name: stress
          image: docker.io/lty010722/stress:latest
          ports:
            - containerPort: 12344
        - name: auto-count
          image: docker.io/lty010722/auto-count:latest
          ports:
            - containerPort: 12345
  adjustInterval: 10
  selector:
    matchLabels:
      app: hpa
  metrics:
    cpuPercentage: 0.1
    memoryPercentage: 0.1