apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: default
  labels:
    app: my-app
spec:
  containers:
  - name: nginx
    image: docker.io/library/nginx:latest
    ports:
    - containerPort: 80
