apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: www
          mountPath: /nfsroot/test
  volumes:
    - name: www
      persistentVolumeClaim:
        claimName: my-pvc