apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
    - name: nfs-client
      image: 192.168.3.8:5050/nfs-client
      imagePullPolicy: registry
      ports:
        - containerPort: 80
      volumeMounts:
        - name: www
          mountPath: /nfsroot/test
  volumes:
    - name: www
      persistentVolumeClaim:
        claimName: test-pvc