apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
    - image: docker.io/library/nginx:latest
      name: test-container
      volumeMounts:
        - mountPath: /test
          name: test-volume
  volumes:
    - name: test-volume
      nfs:
        server: 192.168.3.6
        path: /nfsroot/test