apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
    - name: nginx
      image: docker.io/lty010722/nfs-client:v1
      ports:
        - containerPort: 80
      volumeMounts:
        - name: www
          mountPath: /nfsroot/test
  volumes:
    - name: www
      persistentVolumeClaim:
        claimName: test-pvc