name: test all cases and build

on:
    push:
        branches: ["master", "dev", "feature/*"]

    pull_request:
        branches: ["master", "dev", "feature/*"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.22.2

            - name: Download etcd
              run: |
                wget https://github.com/etcd-io/etcd/releases/download/v3.5.13/etcd-v3.5.13-linux-amd64.tar.gz
                tar -zxvf etcd-v3.5.13-linux-amd64.tar.gz
                cd etcd-v3.5.13-linux-amd64
                ./etcd &

            - name: Run tests
              run: sudo go test ./...

            - name: Build kubectl
              run: sudo go build -o ./build/kubectl ./cmd
