name: test all cases

on:
    push:
        branches: ["master", "dev", "feature/*"]

    pull_request:
        branches: ["master", "dev", "feature/*"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.22.2

            - name: Download etcd
              run: |
                wget https://github.com/etcd-io/etcd/releases/download/v3.5.13/etcd-v3.5.13-linux-amd64.tar.gz
                tar -zxvf etcd-v3.5.13-linux-amd64.tar.gz
                cd etcd-v3.5.13-linux-amd64
                ./etcd &

            - name: Download Kafka
              run: |
                sudo apt-get update
                sudo apt-get install openjdk-8-jdk
                wget https://archive.apache.org/dist/kafka/3.6.0/kafka_2.13-3.6.0.tgz
                tar -zxvf kafka_2.13-3.6.0.tgz
                cd kafka_2.13-3.6.0
                KAFKA_CLUSTER_ID="$(bin/kafka-storage.sh random-uuid)"
                bin/kafka-storage.sh format -t $KAFKA_CLUSTER_ID -c config/kraft/server.properties
                bin/kafka-server-start.sh config/kraft/server.properties &

            - name: Run tests
              run: sudo go test ./...